#!/bin/bash

read -p "When will the meeting be held? " -e dateheld
read -p "Datecode: " -e input

mkdir bt-agd-$input-0.1-mh
echo "bt-agd-$input-mh:
	pdflatex bt-agd-$input-0.1-mh.tex
	pdflatex bt-agd-$input-0.1-mh.tex
	rm *.aux *.log *.toc" > bt-agd-$input-0.1-mh/Makefile
echo '\documentclass[a4paper, 10pt]{article}

\usepackage[dutch]{babel}
\usepackage{url}

\begin{document}

\frenchspacing
\title{Agenda '$dateheld'\\bt-agd-'$input'-mh-0.1}
\author{Menno Hellinga}
\date{\empty}

\maketitle

\newpage
\tableofcontents

\newpage
\section{Hoe ver zijn we?}

\subsection{Menno}
\begin{itemize}
\end{itemize}

\subsection{Nander}
\begin{itemize}
\end{itemize}

\subsection{Dylan}
\begin{itemize}
\end{itemize}

\subsection{Jan Chr.}
\begin{itemize}
\end{itemize}

\subsection{Rik}
\begin{itemize}
\end{itemize}

\newpage

\newpage
\section{WVTTK}

\end{document}' > bt-agd-$input-0.1-mh/bt-agd-$input-0.1-mh.tex
