#!/bin/bash

read -p "When was the meeting held? " -e input

mkdir bt-not-$input-mh
echo "bt-not-$input-mh:
	pdflatex bt-not-$input-mh.tex
	pdflatex bt-not-$input-mh.tex
	rm *.aux *.log *.toc" > bt-not-$input-mh/Makefile
echo '\documentclass[a4paper, 10pt]{article}

\usepackage[dutch]{babel}
\usepackage{url}

\begin{document}

\frenchspacing

\title{Notulen \today\\bt-not-'$input'-mh}
\author{Menno Hellinga}
\date{\empty}

\maketitle
\tableofcontents
\newpage

\section{Aanwezigen}

\section{Hoe ver zijn we?}

\subsection{Menno}
\begin{itemize}
	\item
\end{itemize}

\subsection{Nander}
\begin{itemize}
	\item
\end{itemize}

\subsection{Dylan}
\begin{itemize}
	\item
\end{itemize}

\subsection{Jan Chr.}
\begin{itemize}
	\item
\end{itemize}

\subsection{Rik}
\begin{itemize}
	\item
\end{itemize}

\end{document}' > bt-not-$input-mh/bt-not-$input-mh.tex
